'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AoE2DE_Scenario_Maker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _invalid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_invalid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_non_navigable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_non_navigable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_non_navigable_wet_gravel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_non_navigable_wet_gravel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_non_navigable_wet_rock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_non_navigable_wet_rock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_non_navigable_wet_sand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_non_navigable_wet_sand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_vegetation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_vegetation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_wet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_wet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_wet_gravel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_wet_gravel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_wet_rock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_wet_rock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beach_white_vegetation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beach_white_vegetation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desert_cracked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desert_cracked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desert_quicksand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desert_quicksand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desert_sand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desert_sand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_mud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_mud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt_savannah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt_savannah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farm_0p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm_0p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farm_33p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm_33p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farm_67p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm_67p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farm_dead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm_dead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_acacia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_acacia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_autumn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_autumn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_autumn_snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_autumn_snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_bamboo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_bamboo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_baobab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_baobab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_birch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_birch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_bush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_bush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_dead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_dead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_dragon_tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_dragon_tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_jungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_jungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_mangrove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_mangrove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_mediterrane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_mediterrane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_oak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_oak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_oak_bush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_oak_bush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_palm_desert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_palm_desert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_palm_grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_palm_grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_pine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_pine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_pine_snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_pine_snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_rainforest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_rainforest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_reeds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_reeds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_reeds_beach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_reeds_beach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_reeds_shallows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_reeds_shallows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_dry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_dry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_foundation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_foundation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_jungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_jungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_jungle_rainforest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_jungle_rainforest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_other() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_other", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gravel_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gravel_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gravel_desert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gravel_desert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ice_navigable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice_navigable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rice_farm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice_farm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rice_farm_0p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice_farm_0p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rice_farm_33p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice_farm_33p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rice_farm_66p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice_farm_66p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rice_farm_dead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rice_farm_dead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property road() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property road_broken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road_broken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property road_fungus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road_fungus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property road_gravel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road_gravel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rock_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rock_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shallows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shallows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shallows_azure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shallows_azure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shallows_mangrove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shallows_mangrove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snow_foundation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow_foundation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snow_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snow_strong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow_strong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property swamp_bogland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swamp_bogland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property swamp_shallows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swamp_shallows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property underbrush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underbrush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property underbrush_jungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underbrush_jungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property underbrush_leaves() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underbrush_leaves", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property underbrush_snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underbrush_snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_2d_bridge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_2d_bridge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_2d_shoreless() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_2d_shoreless", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_azure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_azure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_brown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_brown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_deep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_deep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_deep_ocean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_deep_ocean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_shallow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_shallow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
